// <auto-generated />
using BackendMisProductos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendMisProductos.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20241026144441_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendMisClientes.Models.Cliente", b =>
                {
                    b.Property<int>("codigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoCliente"));

                    b.Property<int>("NIT")
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("categoriaCliente")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("estadoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("codigoCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("BackendMisProductos.Models.Producto", b =>
                {
                    b.Property<int>("codigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoProducto"));

                    b.Property<int>("codigoProveedor")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("existenciaMinima")
                        .HasColumnType("int");

                    b.Property<string>("fechaVencimiento")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ubicacionFisica")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("codigoProducto");

                    b.ToTable("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
